2024-08-28 21:54:00,501 - root - INFO - Logging configurado correctamente.
2024-08-28 21:54:00,502 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 21:54:00,503 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 21:56:03,411 - root - INFO - Logging configurado correctamente.
2024-08-28 21:56:03,412 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 21:56:03,412 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 21:56:11,998 - root - INFO - Logging configurado correctamente.
2024-08-28 21:56:11,999 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 21:56:11,999 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:03:30,172 - root - INFO - Logging configurado correctamente.
2024-08-28 22:03:30,173 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:03:30,175 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:03:31,307 - root - INFO - Logging configurado correctamente.
2024-08-28 22:03:31,308 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:03:31,308 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:03:53,436 - root - INFO - Logging configurado correctamente.
2024-08-28 22:03:53,437 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:03:53,438 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:11:22,920 - root - INFO - Logging configurado correctamente.
2024-08-28 22:11:22,921 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:11:22,922 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:12:34,887 - root - INFO - Logging configurado correctamente.
2024-08-28 22:12:34,888 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:12:34,888 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:16:02,132 - root - INFO - Logging configurado correctamente.
2024-08-28 22:16:02,133 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:16:02,133 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:16:02,303 - root - INFO - Logging configurado correctamente.
2024-08-28 22:16:02,304 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:16:02,304 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:17:23,539 - root - INFO - Logging configurado correctamente.
2024-08-28 22:17:23,539 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:17:23,540 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:17:46,680 - root - INFO - Logging configurado correctamente.
2024-08-28 22:17:46,680 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:17:46,680 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:17:59,469 - root - INFO - Logging configurado correctamente.
2024-08-28 22:17:59,470 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:17:59,470 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:18:21,166 - root - INFO - Logging configurado correctamente.
2024-08-28 22:18:21,167 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:18:21,167 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:19:17,457 - root - INFO - Logging configurado correctamente.
2024-08-28 22:19:17,458 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:19:17,458 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:23:04,319 - root - INFO - Logging configurado correctamente.
2024-08-28 22:23:04,320 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:23:04,321 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:23:19,128 - root - INFO - Logging configurado correctamente.
2024-08-28 22:23:19,129 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:23:19,130 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:35:01,560 - root - INFO - Logging configurado correctamente.
2024-08-28 22:35:01,561 - root - INFO - Buffer creado con 0 archivos .chsheet.
2024-08-28 22:35:01,561 - root - INFO - Buffer cargado con 0 archivos.
2024-08-28 22:45:42,690 - root - INFO - Logging configurado correctamente.
2024-08-28 22:45:42,693 - root - INFO - Buffer creado con 2 archivos .chsheet.
2024-08-28 22:45:42,694 - root - INFO - Buffer cargado con 2 archivos.
2024-08-28 22:46:36,432 - root - INFO - Logging configurado correctamente.
2024-08-28 22:46:36,433 - root - INFO - Buffer creado con 2 archivos .chsheet.
2024-08-28 22:46:36,433 - root - INFO - Buffer cargado con 2 archivos.
2024-08-28 23:03:09,308 - root - INFO - Logging configurado correctamente.
2024-08-28 23:03:42,141 - root - INFO - Logging configurado correctamente.
2024-08-29 00:31:18,786 - root - INFO - Logging configurado correctamente.
2024-08-29 00:31:18,838 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-08-29 00:31:18,838 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-08-29 00:31:18,876 - werkzeug - INFO -  * Restarting with watchdog (inotify)
2024-08-29 00:31:19,336 - root - INFO - Logging configurado correctamente.
2024-08-29 00:31:19,360 - werkzeug - WARNING -  * Debugger is active!
2024-08-29 00:31:19,363 - werkzeug - INFO -  * Debugger PIN: 688-329-849
2024-08-29 00:34:05,299 - root - INFO - Logging configurado correctamente.
2024-08-29 00:34:05,349 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-08-29 00:34:05,349 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-08-29 00:34:05,378 - werkzeug - INFO -  * Restarting with watchdog (inotify)
2024-08-29 00:34:05,824 - root - INFO - Logging configurado correctamente.
2024-08-29 00:34:05,847 - werkzeug - WARNING -  * Debugger is active!
2024-08-29 00:34:05,848 - werkzeug - INFO -  * Debugger PIN: 688-329-849
2024-08-29 00:35:16,907 - werkzeug - INFO - 127.0.0.1 - - [29/Aug/2024 00:35:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-08-29 00:35:17,142 - werkzeug - INFO - 127.0.0.1 - - [29/Aug/2024 00:35:17] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2024-08-29 00:35:17,169 - werkzeug - INFO - 127.0.0.1 - - [29/Aug/2024 00:35:17] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2024-08-29 00:35:17,383 - werkzeug - INFO - 127.0.0.1 - - [29/Aug/2024 00:35:17] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2024-08-29 00:35:18,036 - werkzeug - INFO - 127.0.0.1 - - [29/Aug/2024 00:35:18] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-08-29 00:37:30,519 - werkzeug - INFO -  * Detected change in '/home/neocronos/Documentos/Python Scripts/open_cheatsheet/app.py', reloading
2024-08-29 00:37:30,522 - werkzeug - INFO -  * Detected change in '/home/neocronos/Documentos/Python Scripts/open_cheatsheet/app.py', reloading
2024-08-29 00:37:30,726 - werkzeug - INFO -  * Restarting with watchdog (inotify)
2024-08-29 00:38:16,568 - root - INFO - Logging configurado correctamente.
2024-08-29 00:38:16,614 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-08-29 00:38:16,615 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-08-29 00:38:16,638 - werkzeug - INFO -  * Restarting with watchdog (inotify)
2024-08-29 00:38:17,077 - root - INFO - Logging configurado correctamente.
2024-08-29 00:38:17,099 - werkzeug - WARNING -  * Debugger is active!
2024-08-29 00:38:17,100 - werkzeug - INFO -  * Debugger PIN: 688-329-849
2024-08-29 00:38:26,303 - werkzeug - INFO - 127.0.0.1 - - [29/Aug/2024 00:38:26] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-08-29 00:38:26,609 - werkzeug - INFO - 127.0.0.1 - - [29/Aug/2024 00:38:26] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-08-29 00:38:26,652 - werkzeug - INFO - 127.0.0.1 - - [29/Aug/2024 00:38:26] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-08-29 00:38:26,902 - werkzeug - INFO - 127.0.0.1 - - [29/Aug/2024 00:38:26] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-08-29 10:40:47,834 - root - INFO - Logging configurado correctamente.
2024-08-29 10:40:47,891 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-08-29 10:40:47,891 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-08-29 10:40:47,926 - werkzeug - INFO -  * Restarting with watchdog (inotify)
2024-08-29 10:40:48,354 - root - INFO - Logging configurado correctamente.
2024-08-29 10:40:48,377 - werkzeug - WARNING -  * Debugger is active!
2024-08-29 10:40:48,378 - werkzeug - INFO -  * Debugger PIN: 688-329-849
2024-09-02 21:42:49,141 - root - INFO - Logging configurado correctamente.
2024-09-02 21:42:49,143 - root - INFO - Buffer creado con 4 archivos .chsheet.
2024-09-02 21:42:49,144 - root - INFO - Buffer cargado con 4 archivos.
2024-09-03 21:26:48,901 - root - INFO - Logging configurado correctamente.
2024-09-03 21:34:08,554 - root - INFO - Logging configurado correctamente.
2024-09-03 21:43:59,562 - root - INFO - Logging configurado correctamente.
2024-09-03 21:43:59,564 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 21:43:59,565 - flet_runtime - INFO - Starting up UDS server on /tmp/lsR8wiXtBF
2024-09-03 21:43:59,566 - flet_runtime - INFO - Flet app has started...
2024-09-03 21:43:59,566 - flet_runtime - INFO - App URL: /tmp/lsR8wiXtBF
2024-09-03 21:43:59,566 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 21:43:59,568 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 21:44:00,823 - flet_runtime - INFO - App session started
2024-09-03 21:44:52,004 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'page' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 89, in save_settings_and_close
    page.window_close()
    ^^^^
NameError: name 'page' is not defined
2024-09-03 21:45:00,064 - root - INFO - Logging configurado correctamente.
2024-09-03 21:45:00,066 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 21:45:00,069 - flet_runtime - INFO - Starting up UDS server on /tmp/JVgh8MNEX7
2024-09-03 21:45:00,070 - flet_runtime - INFO - Flet app has started...
2024-09-03 21:45:00,070 - flet_runtime - INFO - App URL: /tmp/JVgh8MNEX7
2024-09-03 21:45:00,071 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 21:45:00,072 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 21:45:01,513 - flet_runtime - INFO - App session started
2024-09-03 21:45:25,958 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'page' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 89, in save_settings_and_close
    page.window_close()
    ^^^^
NameError: name 'page' is not defined
2024-09-03 21:45:27,797 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'page' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 89, in save_settings_and_close
    page.window_close()
    ^^^^
NameError: name 'page' is not defined
2024-09-03 21:45:28,446 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'page' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 89, in save_settings_and_close
    page.window_close()
    ^^^^
NameError: name 'page' is not defined
2024-09-03 21:45:28,748 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'page' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 89, in save_settings_and_close
    page.window_close()
    ^^^^
NameError: name 'page' is not defined
2024-09-03 21:45:30,332 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'page' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 89, in save_settings_and_close
    page.window_close()
    ^^^^
NameError: name 'page' is not defined
2024-09-03 21:45:31,715 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'page' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 89, in save_settings_and_close
    page.window_close()
    ^^^^
NameError: name 'page' is not defined
2024-09-03 21:48:35,066 - root - INFO - Logging configurado correctamente.
2024-09-03 21:48:35,068 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 21:48:35,069 - flet_runtime - INFO - Starting up UDS server on /tmp/Tkk3Wb2Kzu
2024-09-03 21:48:35,070 - flet_runtime - INFO - Flet app has started...
2024-09-03 21:48:35,070 - flet_runtime - INFO - App URL: /tmp/Tkk3Wb2Kzu
2024-09-03 21:48:35,070 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 21:48:35,070 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 21:48:36,247 - flet_runtime - INFO - App session started
2024-09-03 21:48:44,103 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("module 'flet_core.page' has no attribute 'window_close'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 89, in save_settings_and_close
    ft.page.window_close() #--------------
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'flet_core.page' has no attribute 'window_close'
2024-09-03 22:00:36,935 - root - INFO - Logging configurado correctamente.
2024-09-03 22:00:36,937 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:00:36,939 - flet_runtime - INFO - Starting up UDS server on /tmp/KoV3ZUZcsZ
2024-09-03 22:00:36,939 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:00:36,939 - flet_runtime - INFO - App URL: /tmp/KoV3ZUZcsZ
2024-09-03 22:00:36,939 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:00:36,940 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:00:38,223 - flet_runtime - INFO - App session started
2024-09-03 22:00:45,107 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'new_key_input' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 66, in add_setting
    new_key = new_key_input.value
              ^^^^^^^^^^^^^
NameError: name 'new_key_input' is not defined
2024-09-03 22:01:33,743 - root - INFO - Logging configurado correctamente.
2024-09-03 22:01:33,745 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:01:33,747 - flet_runtime - INFO - Starting up UDS server on /tmp/aLzF4wwF00
2024-09-03 22:01:33,748 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:01:33,748 - flet_runtime - INFO - App URL: /tmp/aLzF4wwF00
2024-09-03 22:01:33,748 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:01:33,749 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:01:34,924 - flet_runtime - INFO - App session started
2024-09-03 22:06:16,598 - root - INFO - Logging configurado correctamente.
2024-09-03 22:06:16,600 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:06:16,601 - flet_runtime - INFO - Starting up UDS server on /tmp/LgszVNF9Yw
2024-09-03 22:06:16,601 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:06:16,602 - flet_runtime - INFO - App URL: /tmp/LgszVNF9Yw
2024-09-03 22:06:16,602 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:06:16,602 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:06:17,722 - flet_runtime - INFO - App session started
2024-09-03 22:06:22,876 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'list_view' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 56, in <lambda>
    ft.IconButton(ft.icons.DELETE, on_click=lambda e: delete_setting(key))
                                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 78, in delete_setting
    update_list_view()
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 82, in update_list_view
    list_view.controls = build_controls() #------------
    ^^^^^^^^^
NameError: name 'list_view' is not defined
2024-09-03 22:10:15,137 - root - INFO - Logging configurado correctamente.
2024-09-03 22:10:15,139 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:10:15,141 - flet_runtime - INFO - Starting up UDS server on /tmp/r2poPKBK9z
2024-09-03 22:10:15,142 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:10:15,143 - flet_runtime - INFO - App URL: /tmp/r2poPKBK9z
2024-09-03 22:10:15,143 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:10:15,144 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:10:16,214 - flet_runtime - INFO - App session started
2024-09-03 22:11:26,917 - root - INFO - Logging configurado correctamente.
2024-09-03 22:11:26,919 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:11:26,920 - flet_runtime - INFO - Starting up UDS server on /tmp/zRkCDF8xCg
2024-09-03 22:11:26,921 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:11:26,921 - flet_runtime - INFO - App URL: /tmp/zRkCDF8xCg
2024-09-03 22:11:26,921 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:11:26,922 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:11:28,056 - flet_runtime - INFO - App session started
2024-09-03 22:12:09,683 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'list_view' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 57, in <lambda>
    ft.IconButton(ft.icons.DELETE, on_click=lambda e: delete_setting(key))
                                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 79, in delete_setting
    update_list_view()
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_list_view
    list_view.controls = build_controls() #------------
    ^^^^^^^^^
NameError: name 'list_view' is not defined
2024-09-03 22:16:46,004 - root - INFO - Logging configurado correctamente.
2024-09-03 22:16:46,006 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:16:46,008 - flet_runtime - INFO - Starting up UDS server on /tmp/YssGxlSrKd
2024-09-03 22:16:46,009 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:16:46,009 - flet_runtime - INFO - App URL: /tmp/YssGxlSrKd
2024-09-03 22:16:46,010 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:16:46,011 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:16:47,502 - flet_runtime - INFO - App session started
2024-09-03 22:18:26,418 - root - INFO - Logging configurado correctamente.
2024-09-03 22:18:26,420 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:18:26,421 - flet_runtime - INFO - Starting up UDS server on /tmp/G1XYIG3gD6
2024-09-03 22:18:26,421 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:18:26,422 - flet_runtime - INFO - App URL: /tmp/G1XYIG3gD6
2024-09-03 22:18:26,422 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:18:26,422 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:18:27,494 - flet_runtime - INFO - App session started
2024-09-03 22:18:39,185 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'SettingsManager' object has no attribute 'new_key_input'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 67, in add_setting
    new_key = self.new_key_input.value
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'SettingsManager' object has no attribute 'new_key_input'
2024-09-03 22:38:13,973 - root - INFO - Logging configurado correctamente.
2024-09-03 22:38:13,975 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:38:13,978 - flet_runtime - INFO - Starting up UDS server on /tmp/zL7Hta6TCd
2024-09-03 22:38:13,979 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:38:13,979 - flet_runtime - INFO - App URL: /tmp/zL7Hta6TCd
2024-09-03 22:38:13,980 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:38:13,980 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:38:15,114 - flet_runtime - INFO - App session started
2024-09-03 22:48:22,245 - root - INFO - Logging configurado correctamente.
2024-09-03 22:48:22,247 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:48:22,249 - flet_runtime - INFO - Starting up UDS server on /tmp/2Vt50qKcNU
2024-09-03 22:48:22,250 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:48:22,251 - flet_runtime - INFO - App URL: /tmp/2Vt50qKcNU
2024-09-03 22:48:22,251 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:48:22,252 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:48:23,403 - flet_runtime - INFO - App session started
2024-09-03 22:48:30,994 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("SettingsManager.run_gui.<locals>.add_setting() missing 1 required positional argument: 'e'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
TypeError: SettingsManager.run_gui.<locals>.add_setting() missing 1 required positional argument: 'e'
2024-09-03 22:48:38,718 - root - INFO - Logging configurado correctamente.
2024-09-03 22:48:38,720 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:48:38,722 - flet_runtime - INFO - Starting up UDS server on /tmp/XsSi21F04A
2024-09-03 22:48:38,723 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:48:38,723 - flet_runtime - INFO - App URL: /tmp/XsSi21F04A
2024-09-03 22:48:38,723 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:48:38,724 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:48:40,036 - flet_runtime - INFO - App session started
2024-09-03 22:57:58,950 - root - INFO - Logging configurado correctamente.
2024-09-03 22:57:58,952 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-03 22:57:58,953 - flet_runtime - INFO - Starting up UDS server on /tmp/fyyfxcidzJ
2024-09-03 22:57:58,954 - flet_runtime - INFO - Flet app has started...
2024-09-03 22:57:58,954 - flet_runtime - INFO - App URL: /tmp/fyyfxcidzJ
2024-09-03 22:57:58,954 - flet_runtime - INFO - Starting Flet View app...
2024-09-03 22:57:58,954 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-03 22:58:00,039 - flet_runtime - INFO - App session started
2024-09-03 22:58:06,604 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("SettingsManager.run_gui.<locals>.add_setting() missing 1 required positional argument: 'e'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
TypeError: SettingsManager.run_gui.<locals>.add_setting() missing 1 required positional argument: 'e'
2024-09-04 10:41:38,643 - root - INFO - Logging configurado correctamente.
2024-09-04 10:41:38,645 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-04 10:41:38,646 - flet_runtime - INFO - Starting up UDS server on /tmp/j8fkOX7RRd
2024-09-04 10:41:38,647 - flet_runtime - INFO - Flet app has started...
2024-09-04 10:41:38,647 - flet_runtime - INFO - App URL: /tmp/j8fkOX7RRd
2024-09-04 10:41:38,647 - flet_runtime - INFO - Starting Flet View app...
2024-09-04 10:41:38,649 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-04 10:41:40,334 - flet_runtime - INFO - App session started
2024-09-04 10:42:00,170 - root - INFO - Logging configurado correctamente.
2024-09-04 10:42:00,171 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-04 10:42:00,173 - flet_runtime - INFO - Starting up UDS server on /tmp/IB9xNSnJv2
2024-09-04 10:42:00,173 - flet_runtime - INFO - Flet app has started...
2024-09-04 10:42:00,173 - flet_runtime - INFO - App URL: /tmp/IB9xNSnJv2
2024-09-04 10:42:00,173 - flet_runtime - INFO - Starting Flet View app...
2024-09-04 10:42:00,174 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-04 10:42:01,281 - flet_runtime - INFO - App session started
2024-09-04 20:32:33,889 - root - INFO - Logging configurado correctamente.
2024-09-04 20:32:33,891 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-04 20:32:33,892 - flet_runtime - INFO - Starting up UDS server on /tmp/691fW6Fwgr
2024-09-04 20:32:33,893 - flet_runtime - INFO - Flet app has started...
2024-09-04 20:32:33,893 - flet_runtime - INFO - App URL: /tmp/691fW6Fwgr
2024-09-04 20:32:33,893 - flet_runtime - INFO - Starting Flet View app...
2024-09-04 20:32:33,894 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-04 20:32:35,470 - flet_runtime - INFO - App session started
2024-09-06 16:12:24,378 - root - INFO - Logging configurado correctamente.
2024-09-06 16:12:24,380 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-06 16:12:24,382 - flet_runtime - INFO - Starting up UDS server on /tmp/tZ4hJVq9fH
2024-09-06 16:12:24,383 - flet_runtime - INFO - Flet app has started...
2024-09-06 16:12:24,383 - flet_runtime - INFO - App URL: /tmp/tZ4hJVq9fH
2024-09-06 16:12:24,383 - flet_runtime - INFO - Starting Flet View app...
2024-09-06 16:12:24,384 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-06 16:12:25,650 - flet_runtime - INFO - App session started
2024-09-06 16:12:45,981 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'list_view' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 77, in <lambda>
    ft.IconButton(ft.icons.DELETE, on_click=lambda e: delete_setting(key))
                                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 125, in delete_setting
    update_list_view()
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 129, in update_list_view
    list_view.controls = build_controls() #------------
    ^^^^^^^^^
NameError: name 'list_view' is not defined
2024-09-11 16:08:17,154 - root - INFO - Logging configurado correctamente.
2024-09-11 16:08:17,156 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-11 16:08:17,157 - flet_runtime - INFO - Starting up UDS server on /tmp/hYsUuLxI5R
2024-09-11 16:08:17,158 - flet_runtime - INFO - Flet app has started...
2024-09-11 16:08:17,158 - flet_runtime - INFO - App URL: /tmp/hYsUuLxI5R
2024-09-11 16:08:17,158 - flet_runtime - INFO - Starting Flet View app...
2024-09-11 16:08:17,159 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-11 16:08:18,310 - flet_runtime - INFO - App session started
2024-09-12 20:56:07,720 - root - INFO - Logging configurado correctamente.
2024-09-12 20:56:07,723 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 20:56:07,724 - flet_runtime - INFO - Starting up UDS server on /tmp/UUn03hFumK
2024-09-12 20:56:07,725 - flet_runtime - INFO - Flet app has started...
2024-09-12 20:56:07,726 - flet_runtime - INFO - App URL: /tmp/UUn03hFumK
2024-09-12 20:56:07,726 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 20:56:07,726 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 20:56:09,343 - flet_runtime - INFO - App session started
2024-09-12 21:08:27,344 - root - INFO - Logging configurado correctamente.
2024-09-12 21:08:27,347 - root - INFO - Logging configurado correctamente.
2024-09-12 21:08:27,352 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:08:27,356 - flet_runtime - INFO - Starting up UDS server on /tmp/QaW0KZUtL3
2024-09-12 21:08:27,357 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:08:27,358 - flet_runtime - INFO - App URL: /tmp/QaW0KZUtL3
2024-09-12 21:08:27,358 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:08:27,359 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:08:28,938 - flet_runtime - INFO - App session started
2024-09-12 21:15:00,765 - root - INFO - Logging configurado correctamente.
2024-09-12 21:15:00,766 - root - INFO - Logging configurado correctamente.
2024-09-12 21:15:00,768 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:15:00,770 - flet_runtime - INFO - Starting up UDS server on /tmp/ZBelbLMQMX
2024-09-12 21:15:00,771 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:15:00,771 - flet_runtime - INFO - App URL: /tmp/ZBelbLMQMX
2024-09-12 21:15:00,771 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:15:00,772 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:15:02,280 - flet_runtime - INFO - App session started
2024-09-12 21:15:08,824 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'list_view' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 75, in <lambda>
    ft.IconButton(ft.icons.DELETE, on_click=lambda e: delete_setting(key))
                                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 123, in delete_setting
    update_list_view()
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 127, in update_list_view
    list_view.controls = build_controls() #------------
    ^^^^^^^^^
NameError: name 'list_view' is not defined
2024-09-12 21:18:36,525 - root - INFO - Logging configurado correctamente.
2024-09-12 21:18:36,526 - root - INFO - Logging configurado correctamente.
2024-09-12 21:18:36,528 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:18:36,530 - flet_runtime - INFO - Starting up UDS server on /tmp/kgYZz0Ockg
2024-09-12 21:18:36,531 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:18:36,531 - flet_runtime - INFO - App URL: /tmp/kgYZz0Ockg
2024-09-12 21:18:36,531 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:18:36,532 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:18:38,356 - flet_runtime - INFO - App session started
2024-09-12 21:18:45,263 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'list_view' is not defined")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 75, in <lambda>
    ft.IconButton(ft.icons.DELETE, on_click=lambda e: delete_setting(key))
                                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 123, in delete_setting
    update_list_view()
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 127, in update_list_view
    list_view.controls = build_controls() #------------
    ^^^^^^^^^
NameError: name 'list_view' is not defined
2024-09-12 21:24:52,066 - root - INFO - Logging configurado correctamente.
2024-09-12 21:24:52,067 - root - INFO - Logging configurado correctamente.
2024-09-12 21:24:52,069 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:24:52,071 - flet_runtime - INFO - Starting up UDS server on /tmp/xPiaPB37H7
2024-09-12 21:24:52,072 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:24:52,072 - flet_runtime - INFO - App URL: /tmp/xPiaPB37H7
2024-09-12 21:24:52,072 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:24:52,073 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:24:53,623 - flet_runtime - INFO - App session started
2024-09-12 21:25:06,184 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("SettingsManager.run_gui.<locals>.add_setting() missing 1 required positional argument: 'e'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
TypeError: SettingsManager.run_gui.<locals>.add_setting() missing 1 required positional argument: 'e'
2024-09-12 21:27:04,168 - root - INFO - Logging configurado correctamente.
2024-09-12 21:27:04,169 - root - INFO - Logging configurado correctamente.
2024-09-12 21:27:22,050 - root - INFO - Logging configurado correctamente.
2024-09-12 21:27:22,051 - root - INFO - Logging configurado correctamente.
2024-09-12 21:27:22,053 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:27:22,055 - flet_runtime - INFO - Starting up UDS server on /tmp/VeUaNcFqeA
2024-09-12 21:27:22,055 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:27:22,056 - flet_runtime - INFO - App URL: /tmp/VeUaNcFqeA
2024-09-12 21:27:22,056 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:27:22,057 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:27:23,779 - flet_runtime - INFO - App session started
2024-09-12 21:28:41,630 - root - INFO - Logging configurado correctamente.
2024-09-12 21:28:41,638 - root - INFO - Logging configurado correctamente.
2024-09-12 21:28:54,550 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:28:54,560 - flet_runtime - INFO - Starting up UDS server on /tmp/fvIYoqb3oV
2024-09-12 21:28:54,565 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:28:54,566 - flet_runtime - INFO - App URL: /tmp/fvIYoqb3oV
2024-09-12 21:28:54,568 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:28:54,572 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:28:56,455 - flet_runtime - INFO - App session started
2024-09-12 21:29:05,483 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("SettingsManager.run_gui.<locals>.add_setting() missing 1 required positional argument: 'e'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
TypeError: SettingsManager.run_gui.<locals>.add_setting() missing 1 required positional argument: 'e'
2024-09-12 21:30:25,650 - root - INFO - Logging configurado correctamente.
2024-09-12 21:30:25,651 - root - INFO - Logging configurado correctamente.
2024-09-12 21:30:25,653 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:30:25,654 - flet_runtime - INFO - Starting up UDS server on /tmp/2s18NsTifM
2024-09-12 21:30:25,655 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:30:25,655 - flet_runtime - INFO - App URL: /tmp/2s18NsTifM
2024-09-12 21:30:25,656 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:30:25,656 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:30:27,706 - flet_runtime - INFO - App session started
2024-09-12 21:30:34,153 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'ControlEvent' object has no attribute 'new_key_input'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 97, in add_setting
    new_key = self.new_key_input
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'ControlEvent' object has no attribute 'new_key_input'
2024-09-12 21:34:09,932 - root - INFO - Logging configurado correctamente.
2024-09-12 21:34:09,936 - root - INFO - Logging configurado correctamente.
2024-09-12 21:34:09,938 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:34:09,940 - flet_runtime - INFO - Starting up UDS server on /tmp/iiZRJ2tJKD
2024-09-12 21:34:09,945 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:34:09,947 - flet_runtime - INFO - App URL: /tmp/iiZRJ2tJKD
2024-09-12 21:34:09,949 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:34:09,951 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:34:11,853 - flet_runtime - INFO - App session started
2024-09-12 21:34:22,735 - root - INFO - Logging configurado correctamente.
2024-09-12 21:34:22,736 - root - INFO - Logging configurado correctamente.
2024-09-12 21:34:22,737 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:34:22,739 - flet_runtime - INFO - Starting up UDS server on /tmp/H5VKarucy4
2024-09-12 21:34:22,740 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:34:22,740 - flet_runtime - INFO - App URL: /tmp/H5VKarucy4
2024-09-12 21:34:22,740 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:34:22,741 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:34:24,237 - flet_runtime - INFO - App session started
2024-09-12 21:34:30,104 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'SettingsManager' object has no attribute 'save_settings'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 135, in save_settings_and_close
    self.save_settings()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'SettingsManager' object has no attribute 'save_settings'. Did you mean: 'temp_settings'?
2024-09-12 21:45:48,270 - root - INFO - Logging configurado correctamente.
2024-09-12 21:45:48,271 - root - INFO - Logging configurado correctamente.
2024-09-12 21:45:48,273 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:45:48,275 - flet_runtime - INFO - Starting up UDS server on /tmp/fpFdYbTvPy
2024-09-12 21:45:48,276 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:45:48,276 - flet_runtime - INFO - App URL: /tmp/fpFdYbTvPy
2024-09-12 21:45:48,276 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:45:48,277 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:45:49,725 - flet_runtime - INFO - App session started
2024-09-12 21:45:56,225 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 21:45:56,422 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 21:45:56,615 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 21:46:07,082 - root - INFO - Logging configurado correctamente.
2024-09-12 21:46:07,083 - root - INFO - Logging configurado correctamente.
2024-09-12 21:46:07,085 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:46:07,086 - flet_runtime - INFO - Starting up UDS server on /tmp/Rci16xjwUV
2024-09-12 21:46:07,087 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:46:07,087 - flet_runtime - INFO - App URL: /tmp/Rci16xjwUV
2024-09-12 21:46:07,088 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:46:07,088 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:46:08,623 - flet_runtime - INFO - App session started
2024-09-12 21:46:13,160 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 21:46:13,378 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 21:46:13,576 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 21:46:14,511 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 21:50:28,812 - root - INFO - Logging configurado correctamente.
2024-09-12 21:50:28,816 - root - INFO - Logging configurado correctamente.
2024-09-12 21:51:22,993 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 21:51:23,005 - flet_runtime - INFO - Starting up UDS server on /tmp/aWhuqMOSJR
2024-09-12 21:51:23,010 - flet_runtime - INFO - Flet app has started...
2024-09-12 21:51:23,012 - flet_runtime - INFO - App URL: /tmp/aWhuqMOSJR
2024-09-12 21:51:23,014 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 21:51:23,018 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 21:51:24,798 - flet_runtime - INFO - App session started
2024-09-12 21:51:27,704 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 21:51:44,672 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:10:30,983 - root - INFO - Logging configurado correctamente.
2024-09-12 22:10:30,987 - root - INFO - Logging configurado correctamente.
2024-09-12 22:10:30,991 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:10:30,996 - flet_runtime - INFO - Starting up UDS server on /tmp/yXd8Vsvbfg
2024-09-12 22:10:30,999 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:10:31,004 - flet_runtime - INFO - App URL: /tmp/yXd8Vsvbfg
2024-09-12 22:10:31,005 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:10:31,006 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:10:32,843 - flet_runtime - INFO - App session started
2024-09-12 22:10:35,536 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=ValueError("invalid literal for int() with base 10: 'selected_template2'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[int(key)] = value
                       ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'selected_template2'
2024-09-12 22:10:35,769 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=ValueError("invalid literal for int() with base 10: 'selected_template2'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[int(key)] = value
                       ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'selected_template2'
2024-09-12 22:10:35,937 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=ValueError("invalid literal for int() with base 10: 'selected_template2'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[int(key)] = value
                       ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'selected_template2'
2024-09-12 22:10:46,801 - root - INFO - Logging configurado correctamente.
2024-09-12 22:10:46,803 - root - INFO - Logging configurado correctamente.
2024-09-12 22:10:46,807 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:10:46,811 - flet_runtime - INFO - Starting up UDS server on /tmp/cKbKLssbPy
2024-09-12 22:10:46,812 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:10:46,813 - flet_runtime - INFO - App URL: /tmp/cKbKLssbPy
2024-09-12 22:10:46,814 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:10:46,815 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:10:49,067 - flet_runtime - INFO - App session started
2024-09-12 22:11:30,251 - root - INFO - Logging configurado correctamente.
2024-09-12 22:11:30,252 - root - INFO - Logging configurado correctamente.
2024-09-12 22:11:30,254 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:11:30,255 - flet_runtime - INFO - Starting up UDS server on /tmp/gjrK6LyPJk
2024-09-12 22:11:30,256 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:11:30,257 - flet_runtime - INFO - App URL: /tmp/gjrK6LyPJk
2024-09-12 22:11:30,257 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:11:30,258 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:11:32,088 - flet_runtime - INFO - App session started
2024-09-12 22:11:35,767 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=ValueError("invalid literal for int() with base 10: 'selected_template2'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 77, in <lambda>
    ft.IconButton(ft.icons.DELETE, on_click=lambda e: delete_setting(key))
                                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 124, in delete_setting
    del temp_settings[int(key)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'selected_template2'
2024-09-12 22:12:48,629 - root - INFO - Logging configurado correctamente.
2024-09-12 22:12:48,629 - root - INFO - Logging configurado correctamente.
2024-09-12 22:12:48,631 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:12:48,633 - flet_runtime - INFO - Starting up UDS server on /tmp/2IVJEnJIK9
2024-09-12 22:12:48,634 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:12:48,634 - flet_runtime - INFO - App URL: /tmp/2IVJEnJIK9
2024-09-12 22:12:48,634 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:12:48,635 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:12:50,204 - flet_runtime - INFO - App session started
2024-09-12 22:13:06,985 - root - INFO - Logging configurado correctamente.
2024-09-12 22:13:06,985 - root - INFO - Logging configurado correctamente.
2024-09-12 22:13:06,987 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:13:06,989 - flet_runtime - INFO - Starting up UDS server on /tmp/DhI7q8tGby
2024-09-12 22:13:06,990 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:13:06,990 - flet_runtime - INFO - App URL: /tmp/DhI7q8tGby
2024-09-12 22:13:06,991 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:13:06,991 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:13:08,578 - flet_runtime - INFO - App session started
2024-09-12 22:13:29,442 - root - INFO - Logging configurado correctamente.
2024-09-12 22:13:29,443 - root - INFO - Logging configurado correctamente.
2024-09-12 22:13:29,445 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:13:29,447 - flet_runtime - INFO - Starting up UDS server on /tmp/DbisjzNUsp
2024-09-12 22:13:29,447 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:13:29,448 - flet_runtime - INFO - App URL: /tmp/DbisjzNUsp
2024-09-12 22:13:29,448 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:13:29,449 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:13:31,097 - flet_runtime - INFO - App session started
2024-09-12 22:14:45,157 - root - INFO - Logging configurado correctamente.
2024-09-12 22:14:45,160 - root - INFO - Logging configurado correctamente.
2024-09-12 22:20:43,401 - root - INFO - Logging configurado correctamente.
2024-09-12 22:20:43,402 - root - INFO - Logging configurado correctamente.
2024-09-12 22:20:43,404 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:20:43,406 - flet_runtime - INFO - Starting up UDS server on /tmp/o9YfQptkSM
2024-09-12 22:20:43,407 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:20:43,407 - flet_runtime - INFO - App URL: /tmp/o9YfQptkSM
2024-09-12 22:20:43,407 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:20:43,408 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:20:44,967 - flet_runtime - INFO - App session started
2024-09-12 22:22:07,244 - root - INFO - Logging configurado correctamente.
2024-09-12 22:22:07,247 - root - INFO - Logging configurado correctamente.
2024-09-12 22:22:07,251 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:22:07,255 - flet_runtime - INFO - Starting up UDS server on /tmp/srcgihN17s
2024-09-12 22:22:07,257 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:22:07,260 - flet_runtime - INFO - App URL: /tmp/srcgihN17s
2024-09-12 22:22:07,261 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:22:07,263 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:22:08,961 - flet_runtime - INFO - App session started
2024-09-12 22:22:11,742 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'builtin_function_or_method' object is not subscriptable")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 77, in <lambda>
    ft.IconButton(ft.icons.DELETE, on_click=lambda e: delete_setting(key))
                                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 128, in delete_setting
    print[self.temp_settings]
    ~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'builtin_function_or_method' object is not subscriptable
2024-09-12 22:27:22,761 - root - INFO - Logging configurado correctamente.
2024-09-12 22:27:22,762 - root - INFO - Logging configurado correctamente.
2024-09-12 22:27:22,764 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:27:22,766 - flet_runtime - INFO - Starting up UDS server on /tmp/MSnTpx9Okg
2024-09-12 22:27:22,766 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:27:22,767 - flet_runtime - INFO - App URL: /tmp/MSnTpx9Okg
2024-09-12 22:27:22,767 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:27:22,768 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:27:24,080 - flet_runtime - INFO - App session started
2024-09-12 22:27:30,553 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:27:30,713 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:27:30,898 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:27:33,784 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'builtin_function_or_method' object is not subscriptable")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 77, in <lambda>
    ft.IconButton(ft.icons.DELETE, on_click=lambda e: delete_setting(key))
                                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 128, in delete_setting
    print[self.temp_settings]
    ~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'builtin_function_or_method' object is not subscriptable
2024-09-12 22:27:43,869 - root - INFO - Logging configurado correctamente.
2024-09-12 22:27:43,872 - root - INFO - Logging configurado correctamente.
2024-09-12 22:27:43,875 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:27:43,878 - flet_runtime - INFO - Starting up UDS server on /tmp/iko98SMKEA
2024-09-12 22:27:43,880 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:27:43,880 - flet_runtime - INFO - App URL: /tmp/iko98SMKEA
2024-09-12 22:27:43,880 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:27:43,882 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:27:45,281 - flet_runtime - INFO - App session started
2024-09-12 22:28:15,512 - root - INFO - Logging configurado correctamente.
2024-09-12 22:28:15,513 - root - INFO - Logging configurado correctamente.
2024-09-12 22:28:15,515 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:28:15,517 - flet_runtime - INFO - Starting up UDS server on /tmp/JgULulVnNr
2024-09-12 22:28:15,517 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:28:15,518 - flet_runtime - INFO - App URL: /tmp/JgULulVnNr
2024-09-12 22:28:15,518 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:28:15,518 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:28:16,766 - flet_runtime - INFO - App session started
2024-09-12 22:28:28,827 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:28:29,114 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:28:29,338 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 83, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:30:19,470 - root - INFO - Logging configurado correctamente.
2024-09-12 22:30:19,471 - root - INFO - Logging configurado correctamente.
2024-09-12 22:30:19,473 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:30:19,475 - flet_runtime - INFO - Starting up UDS server on /tmp/AinY2a0f1H
2024-09-12 22:30:19,475 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:30:19,476 - flet_runtime - INFO - App URL: /tmp/AinY2a0f1H
2024-09-12 22:30:19,476 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:30:19,477 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:30:20,822 - flet_runtime - INFO - App session started
2024-09-12 22:30:26,168 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 84, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:30:27,440 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 84, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:30:27,886 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 84, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:30:28,415 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 84, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:30:29,534 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 84, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:30:29,998 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 84, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:31:30,611 - root - INFO - Logging configurado correctamente.
2024-09-12 22:31:30,612 - root - INFO - Logging configurado correctamente.
2024-09-12 22:31:30,614 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:31:30,615 - flet_runtime - INFO - Starting up UDS server on /tmp/la2NelMeRZ
2024-09-12 22:31:30,616 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:31:30,616 - flet_runtime - INFO - App URL: /tmp/la2NelMeRZ
2024-09-12 22:31:30,617 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:31:30,617 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:31:31,965 - flet_runtime - INFO - App session started
2024-09-12 22:31:35,714 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 85, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:33:00,813 - root - INFO - Logging configurado correctamente.
2024-09-12 22:33:00,814 - root - INFO - Logging configurado correctamente.
2024-09-12 22:33:00,816 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:33:00,818 - flet_runtime - INFO - Starting up UDS server on /tmp/x82TnLDLhP
2024-09-12 22:33:00,819 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:33:00,819 - flet_runtime - INFO - App URL: /tmp/x82TnLDLhP
2024-09-12 22:33:00,819 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:33:00,820 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:33:02,085 - flet_runtime - INFO - App session started
2024-09-12 22:33:05,421 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 85, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:34:49,179 - root - INFO - Logging configurado correctamente.
2024-09-12 22:34:49,180 - root - INFO - Logging configurado correctamente.
2024-09-12 22:34:49,182 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:34:49,185 - flet_runtime - INFO - Starting up UDS server on /tmp/TTg3S83fuk
2024-09-12 22:34:49,186 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:34:49,186 - flet_runtime - INFO - App URL: /tmp/TTg3S83fuk
2024-09-12 22:34:49,187 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:34:49,188 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:34:50,704 - flet_runtime - INFO - App session started
2024-09-12 22:34:55,045 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object does not support item assignment")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 76, in <lambda>
    ft.TextField(value=str(value), expand=2, on_change=lambda e: update_temp_settings(key, e.control.value)),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 86, in update_temp_settings
    self.temp_settings[key] = value
    ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'str' object does not support item assignment
2024-09-12 22:35:47,244 - root - INFO - Logging configurado correctamente.
2024-09-12 22:35:47,246 - root - INFO - Logging configurado correctamente.
2024-09-12 22:35:47,247 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:35:47,249 - flet_runtime - INFO - Starting up UDS server on /tmp/yAnJWwCOzR
2024-09-12 22:35:47,249 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:35:47,249 - flet_runtime - INFO - App URL: /tmp/yAnJWwCOzR
2024-09-12 22:35:47,250 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:35:47,250 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:35:48,898 - flet_runtime - INFO - App session started
2024-09-12 22:36:13,898 - root - INFO - Logging configurado correctamente.
2024-09-12 22:36:13,899 - root - INFO - Logging configurado correctamente.
2024-09-12 22:36:13,902 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:36:13,904 - flet_runtime - INFO - Starting up UDS server on /tmp/FVWSD2Md43
2024-09-12 22:36:13,906 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:36:13,906 - flet_runtime - INFO - App URL: /tmp/FVWSD2Md43
2024-09-12 22:36:13,906 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:36:13,907 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:36:15,912 - flet_runtime - INFO - App session started
2024-09-12 22:36:25,705 - root - INFO - Logging configurado correctamente.
2024-09-12 22:36:25,707 - root - INFO - Logging configurado correctamente.
2024-09-12 22:36:25,709 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:36:25,711 - flet_runtime - INFO - Starting up UDS server on /tmp/DwLyTmHeXZ
2024-09-12 22:36:25,711 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:36:25,712 - flet_runtime - INFO - App URL: /tmp/DwLyTmHeXZ
2024-09-12 22:36:25,712 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:36:25,713 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:36:27,261 - flet_runtime - INFO - App session started
2024-09-12 22:40:31,161 - root - INFO - Logging configurado correctamente.
2024-09-12 22:40:31,162 - root - INFO - Logging configurado correctamente.
2024-09-12 22:40:31,164 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:40:31,166 - flet_runtime - INFO - Starting up UDS server on /tmp/eE9hclflYe
2024-09-12 22:40:31,167 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:40:31,167 - flet_runtime - INFO - App URL: /tmp/eE9hclflYe
2024-09-12 22:40:31,168 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:40:31,168 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:40:32,666 - flet_runtime - INFO - App session started
2024-09-12 22:40:48,539 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'ControlEvent' object has no attribute 'new_key_input'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 103, in add_setting
    new_key = self.new_key_input
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'ControlEvent' object has no attribute 'new_key_input'
2024-09-12 22:42:10,160 - root - INFO - Logging configurado correctamente.
2024-09-12 22:42:10,161 - root - INFO - Logging configurado correctamente.
2024-09-12 22:42:10,163 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:42:10,164 - flet_runtime - INFO - Starting up UDS server on /tmp/tyEWmy0Pu6
2024-09-12 22:42:10,165 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:42:10,165 - flet_runtime - INFO - App URL: /tmp/tyEWmy0Pu6
2024-09-12 22:42:10,166 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:42:10,166 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:42:11,710 - flet_runtime - INFO - App session started
2024-09-12 22:42:22,405 - root - INFO - Logging configurado correctamente.
2024-09-12 22:42:22,406 - root - INFO - Logging configurado correctamente.
2024-09-12 22:42:22,408 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:42:22,411 - flet_runtime - INFO - Starting up UDS server on /tmp/vbAm9UZPpq
2024-09-12 22:42:22,412 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:42:22,412 - flet_runtime - INFO - App URL: /tmp/vbAm9UZPpq
2024-09-12 22:42:22,413 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:42:22,414 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:42:24,046 - flet_runtime - INFO - App session started
2024-09-12 22:53:56,209 - root - INFO - Logging configurado correctamente.
2024-09-12 22:53:56,212 - root - INFO - Logging configurado correctamente.
2024-09-12 22:53:56,215 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:53:56,218 - flet_runtime - INFO - Starting up UDS server on /tmp/Jv4kcqFFVE
2024-09-12 22:53:56,220 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:53:56,220 - flet_runtime - INFO - App URL: /tmp/Jv4kcqFFVE
2024-09-12 22:53:56,221 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:53:56,222 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:53:57,805 - flet_runtime - INFO - App session started
2024-09-12 22:54:11,840 - root - INFO - Logging configurado correctamente.
2024-09-12 22:54:11,841 - root - INFO - Logging configurado correctamente.
2024-09-12 22:54:11,843 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:54:11,845 - flet_runtime - INFO - Starting up UDS server on /tmp/3z2dGZ8zkw
2024-09-12 22:54:11,845 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:54:11,846 - flet_runtime - INFO - App URL: /tmp/3z2dGZ8zkw
2024-09-12 22:54:11,846 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:54:11,846 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:54:13,441 - flet_runtime - INFO - App session started
2024-09-12 22:56:18,439 - root - INFO - Logging configurado correctamente.
2024-09-12 22:56:18,440 - root - INFO - Logging configurado correctamente.
2024-09-12 22:56:18,442 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 22:56:18,444 - flet_runtime - INFO - Starting up UDS server on /tmp/DWXocH6tVX
2024-09-12 22:56:18,446 - flet_runtime - INFO - Flet app has started...
2024-09-12 22:56:18,446 - flet_runtime - INFO - App URL: /tmp/DWXocH6tVX
2024-09-12 22:56:18,446 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 22:56:18,447 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 22:56:19,940 - flet_runtime - INFO - App session started
2024-09-12 22:56:23,208 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'SettingsManager' object has no attribute 'temp_settings'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 108, in save_settings_and_close
    print(self.temp_settings)
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'SettingsManager' object has no attribute 'temp_settings'
2024-09-12 23:00:07,617 - root - INFO - Logging configurado correctamente.
2024-09-12 23:00:07,620 - root - INFO - Logging configurado correctamente.
2024-09-12 23:00:07,623 - flet_runtime - INFO - Assets path configured: /home/neocronos/Documentos/Python Scripts/open_cheatsheet/assets
2024-09-12 23:00:07,625 - flet_runtime - INFO - Starting up UDS server on /tmp/w87Ip8iZSx
2024-09-12 23:00:07,626 - flet_runtime - INFO - Flet app has started...
2024-09-12 23:00:07,627 - flet_runtime - INFO - App URL: /tmp/w87Ip8iZSx
2024-09-12 23:00:07,627 - flet_runtime - INFO - Starting Flet View app...
2024-09-12 23:00:07,628 - flet_runtime - INFO - Flet View found in: /home/neocronos/.flet/bin/flet-0.23.2
2024-09-12 23:00:09,275 - flet_runtime - INFO - App session started
2024-09-12 23:00:15,765 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'SettingsManager' object has no attribute 'temp_settings'")>
Traceback (most recent call last):
  File "/home/neocronos/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neocronos/anaconda3/lib/python3.12/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/home/neocronos/Documentos/Python Scripts/open_cheatsheet/settings_manager.py", line 110, in save_settings_and_close
    print(self.temp_settings)
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'SettingsManager' object has no attribute 'temp_settings'
